# Generated by Django 4.1.4 on 2022-12-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='НАБОР')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('notice', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('trash_bin', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Набор тестов',
                'verbose_name_plural': 'Наборы тестов',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ТЕСТ')),
                ('editing', models.BooleanField(default=True, verbose_name='Выбран для редактирования')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.topic', verbose_name='НАБОР')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='ВОПРОС')),
                ('accepted', models.BooleanField(default=False, verbose_name='Активирован')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='ТЕСТ')),
                ('topic_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.topic', verbose_name='НАБОР')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответы',
                'verbose_name_plural': 'Вопросы-Ответы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильный ответ')),
                ('quiz_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ТЕСТ')),
                ('topic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='НАБОР')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
