# Generated by Django 4.1.4 on 2022-12-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='НАБОР'),
        ),
        migrations.AlterField(
            model_name='option',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ТЕСТ'),
        ),
        migrations.AlterField(
            model_name='option',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='НАБОР'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz', verbose_name='ТЕСТ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.topic', verbose_name='НАБОР'),
        ),
    ]
