# Generated by Django 4.1.4 on 2022-12-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_option_is_chosen_questionmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmark',
            name='corr_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответы на вопрос'),
        ),
        migrations.AddField(
            model_name='questionmark',
            name='user_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответы студента'),
        ),
        migrations.AlterField(
            model_name='questionmark',
            name='done_correct',
            field=models.BooleanField(),
        ),
    ]
