# Generated by Django 4.1.4 on 2022-12-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionmark_corr_answer_questionmark_user_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_chosen',
        ),
    ]
