# Generated by Django 4.1.4 on 2022-12-30 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_remove_option_is_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор')),
                ('quiz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тест')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оценка')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
