# Generated by Django 4.1.4 on 2022-12-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_errorobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmark',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
