# Generated by Django 4.1.4 on 2023-01-02 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questionmark_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmark',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
