# Generated by Django 4.1.4 on 2023-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_testmark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/topic_pics/'),
        ),
    ]
