# Generated by Django 4.1.4 on 2023-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_topic_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='topic_pics/'),
        ),
    ]
